# Generated by Django 2.0.7 on 2018-08-23 14:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2018, 8, 23, 14, 22, 47, 590820, tzinfo=utc)),
        ),
    ]
