# Generated by Django 2.1.1 on 2018-09-13 19:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180823_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2018, 9, 13, 19, 47, 2, 496311, tzinfo=utc)),
        ),
    ]
